# Generated by Django 3.2.4 on 2023-11-08 02:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_shop', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shop',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='like_users',
            field=models.ManyToManyField(related_name='like_shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
