# Generated by Django 3.2.4 on 2023-11-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20231108_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
