# Generated by Django 3.2.4 on 2023-11-14 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0003_alter_shop_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='dislike_users',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='is_online',
        ),
        migrations.AlterField(
            model_name='shop',
            name='like_users',
            field=models.ManyToManyField(related_name='like_shops', to=settings.AUTH_USER_MODEL),
        ),
    ]
