# Generated by Django 3.2.4 on 2023-11-14 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20231114_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='openhour',
        ),
    ]
